apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculator
  name: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - image: gcr.io/wide-cathode-295207/calculator:latest
        imagePullPolicy: Always
        name: calculator