apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculatortest
  name: calculatortest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculatortest
  template:
    metadata:
      labels:
        app: calculatortest
    spec:
      containers:
      - image: gcr.io/wide-cathode-295207/calculator:latest
        imagePullPolicy: Always
        name: calculatortest