apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculatortest
  name: calculatortest-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: calculatortest
  type: LoadBalancer