apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculator
  name: calculator-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: calculator
  type: LoadBalancer